apiVersion: apps/v1
kind: replicaSet
metadata:
  name: myapp
spec:
  selector:
    matchLabels:
      app: myapp1
  template:
    metadata:
      labels:
        app: myapp1
    spec:
      containers:
      - name: myapp
        image: mylandmarktech/maven-web-app
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080

        
        apiVersion: v1
        kind: Service
        metadata:
          name: mysvc2
        spec: 
          selector:
            app: myapp1
          type: LoadBalancer
          ports:
          - targetPort: 8080
            nodePort: 30202
            port: 80
